apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-monitor-postgres-pvc
  namespace: agricore
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 10Gi