apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abm-postgres-pvc
  namespace: agricore
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abm-postgres-test-pvc
  namespace: agricore
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
